ERROR - 2022-10-17 21:16:54 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'n1604346_siger'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('193.168.194.101', 'n1604346_siger', 'n1604346_siger', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:16:54 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'103.169.238.66' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:19:28 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 171)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://srv65.n...', 'n1604346_siger', 'n1604346_siger', 'n1604346_siger', 3306, '', 0)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#6 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#12 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://srv65.n...', 'n1604346_siger', 'n1604346_siger', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:19:28 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:21:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'n1604346_hiskia'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('193.168.194.101', 'n1604346_hiskia', 'hiskia123', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:21:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'103.169.238.66' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:22:17 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 171)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https:://193.16...', 'n1604346_hiskia', 'hiskia123', 'n1604346_siger', 3306, '', 0)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#6 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#12 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https:://193.16...', 'n1604346_hiskia', 'hiskia123', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:22:17 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:22:38 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 171)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https:://hiskia...', 'n1604346_hiskia', 'hiskia123', 'n1604346_siger', 3306, '', 0)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#6 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#12 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https:://hiskia...', 'n1604346_hiskia', 'hiskia123', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:22:38 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:22:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'n1604346_hiskia'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('hiskia.xyz', 'n1604346_hiskia', 'hiskia123', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:22:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'103.169.238.66' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:26:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'n1604346_hiskia'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('193.168.194.101', 'n1604346_hiskia', 'hiskia123', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:26:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'103.169.238.66' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:32:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'n1604346_hiskia'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('193.168.194.101', 'n1604346_hiskia', 'hiskia123', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:32:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'103.169.238.66' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:34:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'n1604346_siger'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('193.168.194.101', 'n1604346_siger', 'n1604346_siger', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:34:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'103.169.238.66' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 21:35:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'n1604346_siger'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('193.168.194.101', 'n1604346_siger', 'n1604346_siger', 'n1604346_siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'103.169.238.66' (using password: YES) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCod...', Array, false)
#3 C:\laragon\www\sisiger\app\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\sisiger\app\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580...')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580...')
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#10 {main}
CRITICAL - 2022-10-17 21:35:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'103.169.238.66' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `userCode`
FROM `user`
WHERE `uid` = :uid:', [...], false)
 3 APPPATH\Controllers\LikeController.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\LikeController.php(176): App\Controllers\LikeController->getUserCode('109603887362580398656')
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\LikeController->isArchiveArticle('2', '109603887362580398656')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LikeController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-10-17 21:55:52 --> Undefined array key "tourCode"
in APPPATH\Controllers\ArchiveArticleController.php on line 183.
 1 APPPATH\Controllers\ArchiveArticleController.php(183): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "tourCode"', 'APPPATH\\Controllers\\ArchiveArticleController.php', 183)
 2 APPPATH\Controllers\ArchiveArticleController.php(161): App\Controllers\ArchiveArticleController->setThumbTour([...])
 3 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\ArchiveArticleController->allArchiveArticleByUser('109603887362580398656')
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArchiveArticleController))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 22:19:38 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`siger`.`comment_tour`, CONSTRAINT `comment_tour_ibfk_2` FOREIGN KEY (`tourCode`) REFERENCES `tour` (`tourCode`)) in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\sisiger\app\Controllers\CommentArticleController.php(83): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\CommentArticleController->create()
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CommentArticleController))
#11 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2022-10-17 22:19:38 --> Cannot add or update a child row: a foreign key constraint fails (`siger`.`comment_tour`, CONSTRAINT `comment_tour_ibfk_2` FOREIGN KEY (`tourCode`) REFERENCES `tour` (`tourCode`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `comment_tour` (`userCode`, `comment`, `createAt`, `updateAt`) VALUES (\'6\', \'good\', \'2022-10-17 22:19:38\', \'2022-10-17 22:19:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `comment_tour` (`userCode`, `comment`, `createAt`, `updateAt`) VALUES (\'6\', \'good\', \'2022-10-17 22:19:38\', \'2022-10-17 22:19:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `comment_tour` (`userCode`, `comment`, `createAt`, `updateAt`) VALUES (\'6\', \'good\', \'2022-10-17 22:19:38\', \'2022-10-17 22:19:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `comment_tour` (`userCode`, `comment`, `createAt`, `updateAt`) VALUES (:userCode:, :comment:, :createAt:, :updateAt:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\CommentArticleController.php(83): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\CommentArticleController->create()
11 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CommentArticleController))
12 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 22:20:05 --> mysqli_sql_exception: Table 'siger.comment_artice' doesn't exist in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SHOW COLUMNS FR...', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SHOW COLUMNS FR...')
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SHOW COLUMNS FR...')
#3 C:\laragon\www\sisiger\app\Helpers\general_helper.php(12): CodeIgniter\Database\BaseConnection->query('SHOW COLUMNS FR...')
#4 C:\laragon\www\sisiger\app\Models\CommentArticleModel.php(27): allfields('comment_artice')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Config\Factories.php(126): App\Models\CommentArticleModel->__construct(NULL)
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Config\Factories.php(83): CodeIgniter\Config\Factories::__callStatic('models', Array)
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Common.php(817): CodeIgniter\Config\Factories::models('App\\Models\\Comm...', Array, NULL)
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\RESTful\BaseResource.php(54): model('App\\Models\\Comm...')
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\RESTful\BaseResource.php(37): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\Comm...')
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(870): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#11 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#12 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#14 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2022-10-17 22:20:05 --> Table 'siger.comment_artice' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SHOW COLUMNS FROM comment_artice;', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SHOW COLUMNS FROM comment_artice;')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SHOW COLUMNS FROM comment_artice;')
 4 APPPATH\Helpers\general_helper.php(12): CodeIgniter\Database\BaseConnection->query('SHOW COLUMNS FROM comment_artice;')
 5 APPPATH\Models\CommentArticleModel.php(27): allfields('comment_artice')
 6 SYSTEMPATH\Config\Factories.php(126): App\Models\CommentArticleModel->__construct(null)
 7 SYSTEMPATH\Config\Factories.php(83): CodeIgniter\Config\Factories::__callStatic('models', [...])
 8 SYSTEMPATH\Common.php(817): CodeIgniter\Config\Factories::models('App\\Models\\CommentArticleModel', [...], null)
 9 SYSTEMPATH\RESTful\BaseResource.php(54): model('App\\Models\\CommentArticleModel')
10 SYSTEMPATH\RESTful\BaseResource.php(37): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\CommentArticleModel')
11 SYSTEMPATH\CodeIgniter.php(870): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-10-17 22:21:15 --> mysqli_sql_exception: Unknown column 'atCode' in 'order clause' in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `comment...', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `comment...')
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `comment...')
#3 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `comment...', Array, false)
#4 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\sisiger\app\Controllers\CommentArticleController.php(39): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\CommentArticleController->show('2')
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CommentArticleController))
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#12 {main}
CRITICAL - 2022-10-17 22:21:15 --> Unknown column 'atCode' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `comment_article`.*, `user`.`name`, `user`.`image`
FROM `comment_article`
JOIN `user` ON `user`.`userCode`=`comment_article`.`userCode`
WHERE `comment_article`.`articleCode` = \'2\'
ORDER BY `atCode` DESC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `comment_article`.*, `user`.`name`, `user`.`image`
FROM `comment_article`
JOIN `user` ON `user`.`userCode`=`comment_article`.`userCode`
WHERE `comment_article`.`articleCode` = \'2\'
ORDER BY `atCode` DESC')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `comment_article`.*, `user`.`name`, `user`.`image`
FROM `comment_article`
JOIN `user` ON `user`.`userCode`=`comment_article`.`userCode`
WHERE `comment_article`.`articleCode` = \'2\'
ORDER BY `atCode` DESC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `comment_article`.*, `user`.`name`, `user`.`image`
FROM `comment_article`
JOIN `user` ON `user`.`userCode`=`comment_article`.`userCode`
WHERE `comment_article`.`articleCode` = :comment_article.articleCode:
ORDER BY `atCode` DESC', [...], false)
 5 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\CommentArticleController.php(39): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\CommentArticleController->show('2')
 9 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CommentArticleController))
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
