ERROR - 2022-10-03 08:30:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'siger', 3306, '', 0)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\sisiger\app\Helpers\general_helper.php(12): CodeIgniter\Database\BaseConnection->query('SHOW COLUMNS FR...')
#4 C:\laragon\www\sisiger\app\Models\StateModel.php(27): allfields('state')
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Config\Factories.php(126): App\Models\StateModel->__construct(NULL)
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Config\Factories.php(83): CodeIgniter\Config\Factories::__callStatic('models', Array)
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Common.php(817): CodeIgniter\Config\Factories::models('App\\Models\\Stat...', Array, NULL)
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\RESTful\BaseResource.php(54): model('App\\Models\\Stat...')
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\RESTful\BaseResource.php(37): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\Stat...')
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(870): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#11 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#12 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#14 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\sisiger\app\Helpers\general_helper.php(12): CodeIgniter\Database\BaseConnection->query('SHOW COLUMNS FR...')
#3 C:\laragon\www\sisiger\app\Models\StateModel.php(27): allfields('state')
#4 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Config\Factories.php(126): App\Models\StateModel->__construct(NULL)
#5 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Config\Factories.php(83): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Common.php(817): CodeIgniter\Config\Factories::models('App\\Models\\Stat...', Array, NULL)
#7 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\RESTful\BaseResource.php(54): model('App\\Models\\Stat...')
#8 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\RESTful\BaseResource.php(37): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\Stat...')
#9 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(870): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#10 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#11 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\sisiger\public\index.php(73): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2022-10-03 08:30:52 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Helpers\general_helper.php(12): CodeIgniter\Database\BaseConnection->query('SHOW COLUMNS FROM state;')
 3 APPPATH\Models\StateModel.php(27): allfields('state')
 4 SYSTEMPATH\Config\Factories.php(126): App\Models\StateModel->__construct(null)
 5 SYSTEMPATH\Config\Factories.php(83): CodeIgniter\Config\Factories::__callStatic('models', [...])
 6 SYSTEMPATH\Common.php(817): CodeIgniter\Config\Factories::models('App\\Models\\StateModel', [...], null)
 7 SYSTEMPATH\RESTful\BaseResource.php(54): model('App\\Models\\StateModel')
 8 SYSTEMPATH\RESTful\BaseResource.php(37): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\StateModel')
 9 SYSTEMPATH\CodeIgniter.php(870): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
10 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-10-03 08:31:14 --> Too few arguments to function CodeIgniter\Database\BaseBuilder::orderBy(), 0 passed in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Model.php on line 772 and at least 1 expected
in SYSTEMPATH\Database\BaseBuilder.php on line 1408.
 1 SYSTEMPATH\Model.php(772): CodeIgniter\Database\BaseBuilder->orderBy()
 2 APPPATH\Controllers\StateController.php(26): CodeIgniter\Model->__call('orderBy', [])
 3 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\StateController->index()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\StateController))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-10-03 08:31:20 --> Too few arguments to function CodeIgniter\Database\BaseBuilder::orderBy(), 0 passed in C:\laragon\www\sisiger\vendor\codeigniter4\framework\system\Model.php on line 772 and at least 1 expected
in SYSTEMPATH\Database\BaseBuilder.php on line 1408.
 1 SYSTEMPATH\Model.php(772): CodeIgniter\Database\BaseBuilder->orderBy()
 2 APPPATH\Controllers\StateController.php(26): CodeIgniter\Model->__call('orderBy', [])
 3 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\StateController->index()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\StateController))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
